import Nav from 'components/molecules/Nav'
import Head from 'next/head'
import { styled } from 'stitches.config'


const Main = styled('main', {
  padding:"1em"
})






export default function WithNav({children}) {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
      <Main>
        {children}
      </Main>
    </div>
  )
}
