import { gray, violet } from '@radix-ui/colors'
import { Block } from 'components/molecules/Block'
import Nav from 'components/molecules/Nav'
import { Transaction } from 'components/molecules/Transaction'
import Head from 'next/head'
import Link from 'next/link'
import { useGetBlockchain } from 'services/swr/useGetBlocks'
import { useGetPendingTransactions } from 'services/swr/useGetPendingTransactions'
import { styled } from 'stitches.config'


const Main = styled('main', {
  padding: "1em"
})


const Flex = styled('div', {
  display: "grid",
  gridTemplateColumns: "repeat(auto-fit, minmax(45vw, 1fr))",
  gridGap: "2em"
})



const Card = styled('div', {

})




const RowSpaced = styled('div', {
  display:"flex",
  justifyContent:"space-between",
  alignItems:"center",
})





export default function Home() {


  const { data: blockchain } = useGetBlockchain()
  const { data: pendingTransactions } = useGetPendingTransactions()
  console.log(blockchain)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Main>
        <Flex>
          <Card >
            <RowSpaced>
            <h3 style={{ color: violet.violet12 }}>Blocks</h3>
            <Link href='/block'>View all</Link>
            </RowSpaced>
            
            {blockchain?.map((block, id) => <Block key={block.hash} data={block} />)}
           
          </Card>
          <Card >
          <RowSpaced>
            <h3 style={{ color: violet.violet12 }}>Transactions</h3>
            <Link href='/transaction'>View all</Link>
            </RowSpaced>
            {pendingTransactions?.map((block, id) => <Transaction key={block.hash} data={block} />)}
           
          </Card>
        </Flex>


      </Main>
    </div>
  )
}
